### ISSUE TITLE
Missing conda package screwing up my build

### ISSUE THREAD

**Issue by drcandacemakedamoore** [drcandacemakedamoore/cleanX#47]
For a couple of days, I haven't been able to make an updated build on my machine. Salient log below:

ModuleNotFoundError: No module named 'conda._vendor.auxlib'
Traceback (most recent call last):
  File "setup.py", line 648, in <module>
    zip_safe=False,
  File "D:\bin\anaconda3\envs\cleanX\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "D:\bin\anaconda3\envs\cleanX\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\bin\anaconda3\envs\cleanX\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "D:\bin\anaconda3\envs\cleanX\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 476, in run
    raise RuntimeError('Couldn\'t build {} package'.format(name))
RuntimeError: Couldn't build cleanX package

**Comment by drcandacemakedamoore** [comment]
OK, builds fine on last version of CONDA... 31/12/2021
